// Generated by GitHub Copilot
// filepath: test/index.test.ts
// 生成内容説明: CLIエントリーポイント（bin/index.ts）の主要関数（getProjectNameFromArgs, promptForProjectConfig, copyTemplate, showHelp）に対する基本的なユニットテスト。I/Oやfs/inquirer依存部分はモック化。
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as index from '../bin/index';

// getProjectNameFromArgsのテスト

describe('getProjectNameFromArgs', () => {
  const originalArgv = process.argv;
  afterEach(() => {
    process.argv = originalArgv;
  });
  it('引数がある場合はプロジェクト名を返す', () => {
    process.argv = ['node', 'script.js', 'myapp'];
    expect(index.getProjectNameFromArgs()).toBe('myapp');
  });
  it('引数がない場合はnullを返す', () => {
    process.argv = ['node', 'script.js'];
    expect(index.getProjectNameFromArgs()).toBeNull();
  });
});

// promptForProjectConfigのテスト
// inquirer依存のため一旦省略

// showHelpのテスト

describe('showHelp', () => {
  it('ヘルプメッセージを出力する', () => {
    const spy = vi.spyOn(console, 'log').mockImplementation(() => {});
    index.showHelp();
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });
});

// copyTemplateはfs/inquirer依存が多いため、詳細な統合テストは省略（モック化推奨）
